POST http://localhost:4000/api/patients
Content-Type: application/json

{
  "name": "Test",
  "email": "kkarandikar@gmail.com",
  "address": "Test address",
  "dateOfBirth": "1992-08-07",
  "registeredDate": "2025-02-01"
}