PUT http://localhost:4000/api/patients/223e4567-e89b-12d3-a456-426614174008
Content-Type: application/json

{
  "name": "Test",
  "email": "kaushiktest@email.com",
  "address": "Test address",
  "dateOfBirth": "1992-08-07"
}